//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.flows

import kotlin.Int
import kotlin.Long
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.mapNotNull
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.tdlib.TdApi
import org.drinkless.tdlib.TdApi.UpdateUnreadMessageCount

/**
 * emits topicCount [Int] if number of Saved Messages topics has changed.
 */
fun TelegramFlow.savedMessagesTopicCountFlow(): Flow<Int> =
    this.getUpdatesFlowOfType<TdApi.UpdateSavedMessagesTopicCount>()
    .mapNotNull { it.topicCount }

/**
 * emits [UpdateUnreadMessageCount] if number of unread messages in a chat list has changed. This
 * update is sent only if the message database is used.
 */
fun TelegramFlow.unreadMessageCountFlow(): Flow<UpdateUnreadMessageCount> =
    this.getUpdatesFlowOfType()

/**
 * emits starCount [Long] if the number of Telegram stars owned by the current user has changed.
 */
fun TelegramFlow.ownedStarCountFlow(): Flow<Long> =
    this.getUpdatesFlowOfType<TdApi.UpdateOwnedStarCount>()
    .mapNotNull { it.starCount }
