//
// NOTE: THIS FILE IS AUTO-GENERATED by the "TdApiKtxGenerator".kt
// See: https://github.com/tdlibx/td-ktx-generator/
//
package kotlinx.telegram.coroutines

import kotlin.Long
import kotlinx.telegram.core.TelegramFlow
import org.drinkless.td.libcore.telegram.TdApi
import org.drinkless.td.libcore.telegram.TdApi.InputChatPhoto

/**
 * Suspend function, which deletes a profile photo.
 *
 * @param profilePhotoId Identifier of the profile photo to delete.
 */
suspend fun TelegramFlow.deleteProfilePhoto(profilePhotoId: Long) =
    this.sendFunctionLaunch(TdApi.DeleteProfilePhoto(profilePhotoId))

/**
 * Suspend function, which changes a profile photo for the current user.
 *
 * @param photo Profile photo to set.
 */
suspend fun TelegramFlow.setProfilePhoto(photo: InputChatPhoto?) =
    this.sendFunctionLaunch(TdApi.SetProfilePhoto(photo))
